services:
    vln:
        image: curly/vln_game:latest
        container_name: vln_game
        entrypoint: zsh
        environment:
            - ACCEPT_EULA=Y
            - PRIVACY_CONSENT=Y
            - VNC_PASSWORD=curly
            - RESOLUTION=1920x1080
            # - DISPLAY=${DISPLAY}
            # - QT_GRAPHICSSYSTEM=native
            # - NVIDIA_DRIVER_CAPABILITIES=all
            # - TERM=xterm-256color
            # - XAUTHORITY
        ports:
            - "5955:5900"
            - "6055:80"
        volumes:
            # - $HOME/Projects/VLN/isaac_sim/isaac_files/cache/kit:/isaac-sim/kit/cache:rw
            # - $HOME/Projects/VLN/isaac_sim/isaac_files/cache/ov:$HOME/.cache/ov:rw
            # - $HOME/Projects/VLN/isaac_sim/isaac_files/cache/pip:$HOME/.cache/pip:rw
            # - $HOME/Projects/VLN/isaac_sim/isaac_files/cache/glcache:$HOME/.cache/nvidia/GLCache:rw
            # - $HOME/Projects/VLN/isaac_sim/isaac_files/cache/computecache:$HOME/.nv/ComputeCache:rw
            # - $HOME/Projects/VLN/isaac_sim/isaac_files/logs:$HOME/.nvidia-omniverse/logs:rw
            # - $HOME/Projects/VLN/isaac_sim/isaac_files/data:$HOME/.local/share/ov/data:rw
            # - $HOME/Projects/VLN/isaac_sim/isaac_files/documents:$HOME/Documents:rw
            - /home/junzhewu/Projects/:/root/Projects:rw
            - /media/sdd1/hm3d_dataset:/data:rw
            # - /mnt/workspace/users/huyu/junzhe/VLN_dump:/root/Projects/VLN/ext_dump/:rw
            # - /tmp/.X11-unix:/tmp/.X11-unix:rw
            # - $HOME/.Xauthority:/root/.Xauthority:rw
            - .zshrc:/root/.zshrc:rw
            - .zsh_history:/root/.zsh_history:rw
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [ gpu ]

    vln_isaac:
        image: curly/vln_game:latest
        restart: always
        container_name: vln_game_isaac
        entrypoint: zsh
        environment:
            - ACCEPT_EULA=Y
            - PRIVACY_CONSENT=Y
            - VNC_PASSWORD=curly
            - RESOLUTION=1920x1080
            # - DISPLAY=${DISPLAY}
            # - QT_GRAPHICSSYSTEM=native
            # - NVIDIA_DRIVER_CAPABILITIES=all
            # - TERM=xterm-256color
            # - XAUTHORITY
        ports:
            - "5955:5900"
            - "6055:80"
        volumes:
            # - $HOME/Projects/VLN/isaac_sim/isaac_files/cache/kit:/isaac-sim/kit/cache:rw
            # - $HOME/Projects/VLN/isaac_sim/isaac_files/cache/ov:$HOME/.cache/ov:rw
            # - $HOME/Projects/VLN/isaac_sim/isaac_files/cache/pip:$HOME/.cache/pip:rw
            # - $HOME/Projects/VLN/isaac_sim/isaac_files/cache/glcache:$HOME/.cache/nvidia/GLCache:rw
            # - $HOME/Projects/VLN/isaac_sim/isaac_files/cache/computecache:$HOME/.nv/ComputeCache:rw
            # - $HOME/Projects/VLN/isaac_sim/isaac_files/logs:$HOME/.nvidia-omniverse/logs:rw
            # - $HOME/Projects/VLN/isaac_sim/isaac_files/data:$HOME/.local/share/ov/data:rw
            # - $HOME/Projects/VLN/isaac_sim/isaac_files/documents:$HOME/Documents:rw
            - /home/junzhewu/Projects/:/root/Projects:rw
            - /media/sdd1/hm3d_dataset:/data:rw
            # - /mnt/workspace/users/huyu/junzhe/VLN_dump:/root/Projects/VLN/ext_dump/:rw
            # - /tmp/.X11-unix:/tmp/.X11-unix:rw
            # - $HOME/.Xauthority:/root/.Xauthority:rw
            - .zshrc:/root/.zshrc:rw
            - .zsh_history:/root/.zsh_history:rw
        ulimits:
            nofile:
                soft: 65536
                hard: 65536
        deploy:
            resources:
                reservations:
                    devices:
                        - driver: nvidia
                          count: all
                          capabilities: [ gpu ]
